# Generated by Django 3.1.7 on 2021-06-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_force_left',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='session',
            name='max_force_right',
            field=models.IntegerField(default=10),
        ),
    ]
