# Generated by Django 3.1.7 on 2021-06-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_block', '0002_auto_20210606_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='max_force_left',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_force_right',
            field=models.IntegerField(blank=True),
        ),
    ]
