# Generated by Django 3.1.7 on 2021-06-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_block', '0003_auto_20210607_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='max_force_left',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_force_right',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
